language: csharp
solution: Swin-Adventure.sln

install:
  - nuget restore Swin-Adventure.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Swin-Adventure.sln
  - mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe   ./Swin-Adventure/bin/Debug/nunit.framework.dll
  