language: csharp
solution: Swin-Adventure.sln

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild /p:Configuration=Release Swin-Adventure.sln
  - nunit-console ./Swin-Adventure/bin/Debug/nunit.framework.dll
  
  